### ISSUE TITLE
Fehler in Funktionen-R-Skript 1 (b)

### ISSUE THREAD

**Issue by QQTob** [100gLeberwurst/Wissenschaftliches-Arbeiten#10]
Die Daten in dem ursprünglichen Datensatz sind keine Factors, deswegen funktionieren die plot Funktionen nicht.
Man muss n anders bestimmen, z.B. durch "n<-length(levels(as.factor(v)))" und den label vektor anders machen indem man schreibt: "labels=c("",1:n,"").

**Comment by thorbenkiehl** [comment]
as.factor(daten) würde auch funktionieren

**Comment by thorbenkiehl** [comment]
Zusätzlich in der c) müssen bei den kateg Funktionen noch name1 und name2 ergänzt werden
