### ISSUE TITLE
Frage zu den Quantilen

### ISSUE THREAD

**Issue by 100gLeberwurst** [100gLeberwurst/Wissenschaftliches-Arbeiten#19]
Sollten die Quantile nicht additiv sein?
Also bspw. wenn 5 Werte die kleinsten 33% bilden, 5 Werte die mittleren 33% und 5 Werte die größten 33%.
Wäre dann das 0,33-Quantil nicht 5, das 0,66-Quantil dann entsprechend 10 und das "1,00-Quantil" dann 15? 
Momentan haben wir ja quasi nur die Aufteilung in die 33% niedrigsten, mittleren und höchsten Werte :)

**Comment by RudiZul** [comment]
Wir sollen ja quantilbasiert kategorisieren. In unserer aktuellen Version bekommen wir einen Vektor mit den 3 Ausprägungen "niedrig", "mittel", und "hoch" zurück. Also in deinem Beispiel würden die 5 kleinsten Werte den Wert "niedrig" erhalten usw.
