### ISSUE TITLE
Weiteres Vorgehen

### ISSUE THREAD

**Issue by RudiZul** [100gLeberwurst/Wissenschaftliches-Arbeiten#21]
Wenn ich das richtig sehe, haben wir noch folgende Aufgaben:
- Skript mit Anwendung der Funktionen fertigstellen 
- Dokumentation der Funktionen in Skript 1&2

Wer kümmert sich da um was? 
Ich kann nachher (ab ca. 15.00) die Dokumentation übernehmen, an der Anwendung darf ich ja nicht arbeiten :)

**Comment by 100gLeberwurst** [comment]
Also zur Anwendung der Funktionen hat @QQTob schon was, hat er mir gestern gezeigt, sieht schon fast fertig aus.

**Comment by FelixKrall** [comment]
Ich werd mich auch noch einwenig an der Anwendung, sprich aufgabe 4 beteiligen, denke dann sollte die Aufteilung auch ganz gut passen.

**Comment by RudiZul** [comment]
Alles klar, das klingt doch gut
