### ISSUE TITLE
Functions1 (b)

### ISSUE THREAD

**Issue by QQTob** [100gLeberwurst/Wissenschaftliches-Arbeiten#22]
Habt ihr auch Probleme mit load("Functions2.R") ? 
Bei mir gibt das nur Probleme, obwohl Functions2 in meinem working directory ist.

**Comment by RudiZul** [comment]
Um eine .R Datei einzulesen muss man die Funktion source() aufrufen, statt load().
Kann das einer von euch kurz ändern?

**Comment by FelixKrall** [comment]
Ich kümmere mich drum
