### ISSUE TITLE
Functions1 kleine Änderung Idee

### ISSUE THREAD

**Issue by QQTob** [100gLeberwurst/Wissenschaftliches-Arbeiten#23]
Sollen wir bei den meisten Plot Funktionen noch mfrow=c(1,1) setzen, damit man beim Aufrufen außerhalb der vorgegebenen Reihenfolge auf keine "Fehler" trifft?

**Comment by FelixKrall** [comment]
kann ich auch kurz machen Augenblick

**Comment by RudiZul** [comment]
Das stimmt.
Ich glaube, man kann auch zu Beginn jeder Funktion dev.off() schreiben: Dann schließt sich das Grafikfenster und beim nächsten Aufruf von plot() oder so sollte man die Standardeinstellungen wieder haben (bin mir aber nicht 100% sicher).

Wir können aber auch einfach mfrow=c(1,1) setzen, dann haben wir nur die vorherigen Randeinstellungen noch (sollte ja auch kein großes Problem sein)
