### ISSUE TITLE
dev.off()

### ISSUE THREAD

**Issue by QQTob** [100gLeberwurst/Wissenschaftliches-Arbeiten#29]
Es gibt noch einige Probleme mit dev.off()

**Comment by 100gLeberwurst** [comment]
Kein Bug, sondern ein Feature.

**Comment by RudiZul** [comment]
Was funktioniert denn nicht?

**Comment by FelixKrall** [comment]
ich werd mal das zuerst besprochene par(mfrow = c(1,1)) benutzen, da das ja unser primäres Bedenken war und mit Sicherheit keine Probleme macht.

**Comment by FelixKrall** [comment]
Pull request erstellt und gemerged
