### ISSUE TITLE
Funktionen-R-Skript 1 (f)

### ISSUE THREAD

**Issue by QQTob** [100gLeberwurst/Wissenschaftliches-Arbeiten#4]
sollen alle Variablen in einer Grafik dargestellt werden, oder in mehreren?

**Comment by FelixKrall** [comment]
Bei welcher Aufgabe meinst du jetzt genau?

**Comment by QQTob** [comment]
visualize <- function(data1,data2,data3,data4){
  
  par(mfrow=c(2,2),mar=c(3,6,2,1))
  
  barplot(table(data1)/100,horiz=TRUE,las=1,xlim=c(0,1),col="lightblue",
           xlab="Prozent",main="Studienfach")
  box()
  
  barplot(table(data2)/100,horiz=TRUE,las=1,xlim=c(0,1),col="red4",
          xlab="Prozent",main="MatheLK")
  box()
  
  barplot(table(data3)/100,horiz=TRUE,las=1,xlim=c(0,1),col="green4",
          xlab="Prozent",main="Interesse in Programmieren")
  box()
  
  barplot(table(data4)/100,horiz=TRUE,las=1,xlim=c(0,1),col="darkviolet",
          xlab="Prozent",main="Intersse in Mathe ")
  box()
  
  
}

visualize(daten$studienfach,daten$matheLK,daten$intProg,daten$intMathe)

**Comment by thorbenkiehl** [comment]
soll sich die Funktion wirklich direkt auf die Variablen beziehen? 
Ich dachte das soll allgemein für jeden Datensatz funktionieren, 
also in Bezug auf die überschriftten der Grafiken in der funktion

**Comment by RudiZul** [comment]
@thorbenkiehl Das habe ich auch überlegt. Ich habe ja gerade eine Datei mit einem Vorschlag für f) hochgeladen. Da sind jetzt noch gar keine Beschriftungen eingebaut, aber das können wir da drin ja ergänzen
