### ISSUE TITLE
Helferfunktionen

### ISSUE THREAD

**Issue by thorbenkiehl** [100gLeberwurst/Wissenschaftliches-Arbeiten#9]
Auf welche Funktion wollen wir denn eine Helferfunktion anwenden?
Wenn man jetzt davon ausgeht das wir nur eine benutzen

**Comment by 100gLeberwurst** [comment]
Gute Frage, so ganz bin ich noch nicht dahintergestiegen was genau damit gemeint ist. Bisher funktionieren die geschriebenen Funktionen ja ohne zusätzlichen Code aus anderen Skripts...

**Comment by RudiZul** [comment]
Ich glaube, wir sollen eine Funktion "ausgliedern".
In b) berechnen wir ja z.B. den Modus etwas umständlich. Vielleicht können wir in dem anderen Schritt eine Funktion schrieben, die den Modus zurückgibt und die dann in der Funktion b) aus Skript 1 aufrufen

**Comment by 100gLeberwurst** [comment]
Ok gut, so hab ich das auch verstanden :)
